# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: book
# 書名
booktitle: ことりちゃんと学ぶコンピュテーション式入門(仮)
# 著者
aut: pocketberserker
prt: bleis, mzp
prt_url:  https://github.com/chapter11-patch/
edt: bleis, mzp
dsr: bleis, mzp
date: 2017-4-9
rights: |
  (C) 2017 >>=愛好会
description: コンピュテーション式入門

# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
# coverfile: _cover.html
# coverimage: 表紙用画像ファイル
# coverimage: cover.jpg
# 固有IDに使用するドメイン
urnid: https://github.com/chapter11-patch/computation-expressions
# CSSファイル (yamlファイルおよびReVIEWファイルを置いたディレクトリにあること
#stylesheet: main.css
# LaTeX用のdocumentclassを指定する
texstyle: tatsumacro
texdocumentclass: ["jsbook", "uplatex,oneside,14pt"]
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 2
# review-compileに渡すパラメータ
# params: --stylesheet=main.css
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: true
pubhistory: |
  2017年4月9日  発行したい v0.1.0
debug: true
